### ISSUE TITLE
Stephane's feed-back

### ISSUE THREAD

**Issue by madclam** [zhengying-liu/autodl_starting_kit_stable#4]
- une remarque générale : il y a beaucoup d’informations à récupérer depuis les différents codes du github. Une documentation sur les fonctions attendues de model.py et l’interaction entre le programme "ingestion" et le model.py pourrait éclaircir certains points. 

- Une question qu’on s’est posé : quelle est l’ordre de grandeur du time budget ? Sur la page des résultats sur Codalab, on voit des soumissions allant de quelques heures à plusieurs jours.. Il faudrait peut-être préciser ça, qui aiderait à cibler des approches d’intérêt pour le challenge. Par exemple, est-ce qu’il peut être envisagé des approches grid-search pour déterminer tailles et nombres de couches ?

- Le notebook dit que le Tmax en log scale est 1 ; alors que sur les figures (sur la page principale et le notebook), ce n'est pas le cas. En revanche sur codalab, les timestamp des learning curves sont bien normalisées.

- Que voit on dans les metadata d’un dataset lorsque les données sont de tailles différentes? None ? Faut parcourir toutes les données d’entrainement pour connaitre les tailles min et max ? Est-ce que les données de test seront nécessairement dans cette même intervalle ?

**Comment by zhengying-liu** [comment]
Flow chart added. Updated tutorial.ipynb according to changes in new metric.
