### ISSUE TITLE
Support PyTorch models

### ISSUE THREAD

**Issue by D-X-Y** [zhengying-liu/autodl_starting_kit_stable#8]
Hi, must we use tensorflow for autoDL competition? Is it possible to use PyTorch in models? If so, would you mind to provide an example model code?

In addition, the website (https://autodl.lri.fr/competitions/146) seems down and can not be connected?

**Comment by Didayolo** [comment]
Hi, thank you for your message.

You can use PyTorch for your model. We are going to release one of our PyTorch baseline examples soon.

Regarding the autodl.lri.fr website, we have encountered server issues but now it is up!

**Comment by zhengying-liu** [comment]
Hi, we made a release (https://github.com/zhengying-liu/autodl_starting_kit_stable/commit/a0795c45755b03e8792fcb53b16734da9d6fbf46) which includes a [PyTorch baseline example](https://github.com/zhengying-liu/autodl_starting_kit_stable/blob/master/AutoDL_simple_baseline_models/3dcnn_pytorch/model.py). For PyTorch gurus, you are all welcome to improve this code by making pull requests. :)
