### ISSUE TITLE
Cannot download public dataset

### ISSUE THREAD

**Issue by zhengxiawu** [zhengying-liu/autodl_starting_kit_stable#9]
**Describe the bug**
The download page in the python script is unavailable

![image](https://user-images.githubusercontent.com/6270616/61294636-dea3eb00-a808-11e9-94eb-10a05d4599d5.png)

**Comment by Didayolo** [comment]
Thank you for your feedback. Indeed, the script has been updated on [autodl](https://github.com/zhengying-liu/autodl/tree/master/codalab_competition_bundle/AutoDL_starting_kit) repository but not on this one yet.

**Comment by Didayolo** [comment]
I updated the `download_public_datasets.py' script.

It should be working now. Feel free to re-open an issue if needed.
